### ISSUE TITLE
Syntax error related to bug reported on community.

### ISSUE THREAD

**Issue by dr01d3r** [vanderbilt-redcap/fhir-services-module#1]
https://github.com/vanderbilt-redcap/fhir-services-module/blob/a07d5f338abab96e1597ed792af54809e5735495/SchemaParser.php#L306

https://community.projectredcap.org/questions/122411/error-when-enabling-fhir-services-module-redcap-v1.html?childToView=122861#comment-122861

**Comment by mmcev106** [comment]
This has been fixed in version 2.0.4.  Thanks very much for identifying this @dr01d3r!
